import discord

client = discord.Client()

@client.event
async def on_ready():
    print('We are ready to oof as {0.user}'.format(client)),
    

@client.event
async def on_message(message):
    if message.author == client.user:
        return

    if message.content.startswith('o!hello'):
        await message.channel.send('Hello!')  
        
    elif message.content.startswith('o!oof'):
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
        await message.channel.send('OOF')
   

client.run("BOT TOKEN HERE")
